---
format:
  line_width: 100
  tab_size: 4
  use_tabchars: false
  max_subgroups_hwrap: 2
  max_pargs_hwrap: 4
  max_rows_cmdline: 1
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  dangle_parens: false
  dangle_align: prefix
  min_prefix_chars: 4
  max_prefix_chars: 10
  max_lines_hwrap: 2
  command_case: canonical
  keyword_case: upper
  always_wrap: []
  enable_sort: true
  autosort: false
  require_valid_layout: false
  layout_passes: 2

parse:
  additional_commands:
    # Qt6 CMake API
    qt_add_executable:
      pargs: {nargs: 1+}
      kwargs:
        MANUAL_FINALIZATION: 0
        OUTPUT_DIRECTORY: 1
    qt_add_library:
      pargs: {nargs: 1+}
    qt_add_qml_module:
      pargs: {nargs: 1+}
      kwargs:
        URI: 1
        VERSION: 1
        RESOURCE_PREFIX: 1
        QML_FILES: '*'
        SOURCES: '*'
        IMPORTS: '*'
        DEPENDENCIES: '*'
        OPTIONAL_IMPORTS: '*'
    qt_add_resources:
      pargs: {nargs: 2}
      kwargs:
        FILES: '*'
        PREFIX: 1
    qt_finalize_executable:
      pargs: {nargs: 1}
    qt_finalize_target:
      pargs: {nargs: 1}

markup:
  enable_markup: true
  canonicalize_hashrulers: true
  hashruler_min_length: 10
  first_comment_is_literal: false
