# =============================================================================
# Build summary — call vcic_print_summary() at the end of the top-level CMakeLists.txt to print a
# structured overview of the configuration.
# =============================================================================
# Prints a structured summary of build type, compiler, Qt version, feature checks, and options.
function(vcic_print_summary)
    set(sep "-- ------------------------------------------------------------")

    message(STATUS "")
    message(STATUS "-- ============================================================")
    message(STATUS "--  ${PROJECT_NAME}  v${PROJECT_VERSION}")
    message(STATUS "-- ============================================================")
    message(STATUS "--  Build")
    message(STATUS "--    Type      : ${CMAKE_BUILD_TYPE}")
    message(STATUS "--    Generator : ${CMAKE_GENERATOR}")
    message(STATUS "--    Install   : ${CMAKE_INSTALL_PREFIX}")
    message(STATUS "${sep}")
    message(STATUS "--  Compiler")
    message(STATUS "--    ID        : ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
    message(STATUS "--    Path      : ${CMAKE_CXX_COMPILER}")
    message(STATUS "--    Standard  : C++${CMAKE_CXX_STANDARD}")
    message(STATUS "${sep}")
    message(STATUS "--  Qt")
    message(STATUS "--    Version   : ${Qt6_VERSION}")
    message(STATUS "--    Prefix    : ${Qt6_DIR}")
    message(STATUS "${sep}")
    message(STATUS "--  C++ / Qt feature checks")
    foreach(feature IN LISTS VCIC_CHECKS_PASSED)
        message(STATUS "--    [OK] ${feature}")
    endforeach()
    foreach(feature IN LISTS VCIC_CHECKS_FAILED)
        message(STATUS "--    [--] ${feature}")
    endforeach()
    message(STATUS "${sep}")
    message(STATUS "--  Build options")
    message(STATUS "--    VCIC_BUILD_TESTS          : ${VCIC_BUILD_TESTS}")
    message(STATUS "--    VCIC_BUILD_BENCHMARKS     : ${VCIC_BUILD_BENCHMARKS}")
    message(STATUS "--    VCIC_BUILD_EXAMPLES       : ${VCIC_BUILD_EXAMPLES}")
    message(STATUS "--    VCIC_BUILD_GUI            : ${VCIC_BUILD_GUI}")
    message(STATUS "--    VCIC_ENABLE_CLANG_TIDY    : ${VCIC_ENABLE_CLANG_TIDY}")
    message(STATUS "--    VCIC_ENABLE_SANITIZERS    : ${VCIC_ENABLE_SANITIZERS}")
    message(STATUS "--    VCIC_ENABLE_COVERAGE      : ${VCIC_ENABLE_COVERAGE}")
    message(STATUS "--    VCIC_ENABLE_IPO           : ${VCIC_ENABLE_IPO}")
    message(STATUS "--    VCIC_WARNINGS_AS_ERRORS   : ${VCIC_WARNINGS_AS_ERRORS}")
    message(STATUS "-- ============================================================")
    message(STATUS "")
endfunction()
